# Operadores relacionais

# Igual (=)
# Para veriricar se dois valores são iguais podemos utilizar a 
# instrução "be"q, que vai realizar a comparação entre os valores
# de dois registradores.

# menor (<) e maior (>)
# Para que a comparação relacional  entre valores possa ser 
# realizada, devemos aplicar uma lógica para resolver esse problema.
# A ídeia que eu tive para resolver esse problema foi fazer um contador de 0
# até o valor que primeiro for atingido entre os valores informados, o que for 
# atingido primeiro será o valor menor, dessa forma
# os dois valores informados, devem ser maiores ou iguais a zero.
